export const SEND_GET_GAME_DATA = 'SEND GET GAME DATA';
export const SUCCEED_GET_GAME_DATA = 'SUCCEED GET GAME DATA';
export const FAIL_GET_GAME_DATA = 'FAIL GET GAME DATA';

export const SEND_UPDATE_GAME_DATA = 'SEND UPDATE GAME DATA';
export const SUCCEED_UPDATE_GAME_DATA = 'SUCCEED UPDATE GAME DATA';
export const FAIL_UPDATE_GAME_DATA = 'FAIL UPDATE GAME DATA';

export const SEND_GET_EDITABLE_LEVEL = 'SEND GET EDITABLE LEVEL';
export const SUCCEED_GET_EDITABLE_LEVEL = 'SUCCEED GET EDITABLE LEVEL';
export const FAIL_GET_EDITABLE_LEVEL = 'FAIL GET EDITABLE LEVEL';

export const LOGOUT = 'LOGOUT';
