export const SEND_GET_GAME_DATA = 'SEND_GET_GAME_DATA';
export const SUCCEED_GET_GAME_DATA = 'SUCCEED_GET_GAME_DATA';
export const FAIL_GET_GAME_DATA = 'FAIL_GET_GAME_DATA';

export const SEND_UPDATE_GAME_DATA = 'SEND_UPDATE_GAME_DATA';
export const SUCCEED_UPDATE_GAME_DATA = 'SUCCEED_UPDATE_GAME_DATA';
export const FAIL_UPDATE_GAME_DATA = 'FAIL_UPDATE_GAME_DATA';
export const UPDATE_LOCAL_GAME_DATA = 'UPDATE_LOCAL_GAME_DATA';

export const SEND_GET_EDITABLE_LEVEL = 'SEND_GET_EDITABLE_LEVEL';
export const SUCCEED_GET_EDITABLE_LEVEL = 'SUCCEED_GET_EDITABLE_LEVEL';
export const FAIL_GET_EDITABLE_LEVEL = 'FAIL_GET_EDITABLE_LEVEL';

export const SEND_UPDATE_EDITABLE_LEVEL = 'SEND_UPDATE_EDITABLE_LEVEL';
export const SUCCEED_UPDATE_EDITABLE_LEVEL = 'SUCCEED_UPDATE_EDITABLE_LEVEL';
export const FAIL_UPDATE_EDITABLE_LEVEL = 'FAIL_UPDATE_EDITABLE_LEVEL';
export const UPDATE_LOCAL_EDITABLE_LEVEL = 'UPDATE_LOCAL_EDITABLE_LEVEL';

export const SEND_GET_ACTIVE_GAMES_LIST = 'SEND_GET_ACTIVE_GAMES_LIST';
export const SUCCEED_GET_ACTIVE_GAMES_LIST = 'SUCCEED_GET_ACTIVE_GAMES_LIST';
export const FAIL_GET_ACTIVE_GAMES_LIST = 'FAIL_GET_ACTIVE_GAMES_LIST';
export const SEND_GET_PENDING_GAMES_LIST = 'SEND_GET_PENDING_GAMES_LIST';
export const SUCCEED_GET_PENDING_GAMES_LIST = 'SUCCEED_GET_PENDING_GAMES_LIST';
export const FAIL_GET_PENDING_GAMES_LIST = 'FAIL_GET_PENDING_GAMES_LIST';
export const SEND_GET_INVITATIONS = 'SEND_GET_INVITATIONS';
export const SUCCEED_GET_INVITATIONS = 'SUCCEED_GET_INVITATIONS';
export const FAIL_GET_INVITATIONS = 'FAIL_GET_INVITATIONS';

export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const SEND_GET_OFFLINE_USERS = 'SEND_GET_OFFLINE_USERS';
export const SUCCEED_GET_OFFLINE_USERS = 'SUCCEED_GET_OFFLINE_USERS';
export const FAIL_GET_OFFLINE_USERS = 'FAIL_GET_OFFLINE_USERS';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const UPDATE_NOTIFICATION_CLASSNAME = 'UPDATE_NOTIFICATION_CLASSNAME';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const LOGOUT = 'LOGOUT';
